name: metoceanproviders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netCDF4
  - dask
  - bottleneck
  - lxml
  - pydap
  - scipy

# DEV-PACKAGES
  - python-dotenv
  - flit
  - pytest-cov
  - pip-tools
  - pre-commit
  - coverage-badge
  - black
  # - pip:
  #   - git+https://github.com/IHCantabria/qualitas.downloader.git@v0.3.5 --install-option="--no-deps"
